<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Démineur en JS</title>
	<!-- Styles -->
	<link rel="stylesheet" type="text/css" href="./styles/reset.css">
	<link rel="stylesheet/less" href="styles/mixins.less" />
	<link rel="stylesheet/less" href="styles/style.less" />
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

	<!-- Scripts -->
	<script type="text/javascript" src="scripts/less.min.js"></script>
	<script type="text/javascript" src="scripts/jquery-2.1.4.min.js"></script>
</head>
<body>
	<div>
		<i class="fa fa-bomb fa-2x"></i>
		<i class="fa fa-flag fa-2x"></i>
	</div>
</body>
</html>