<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Démineur en JS</title>
	<!-- Styles -->
	<link rel="stylesheet" type="text/css" href="./styles/reset.css">
	<link rel="stylesheet/less" href="styles/mixins.less" />
	<link rel="stylesheet/less" href="styles/style.less" />

	<!-- Scripts -->
	<script type="text/javascript" src="scripts/less.min.js"></script>
	<script type="text/javascript" src="scripts/jquery-2.1.4.min.js"></script>
	<script type="text/javascript" src="scripts/pixi.js"></script>
<body>
	<div id="container">
		
	</div>
	<!-- Scripts du jeu -->
	<script type="text/javascript" src="scripts/jerome.js"></script>
	<script type="text/javascript" src="scripts/maria.js"></script>

</body>
</html>